### ISSUE TITLE
Assign me work.

### ISSUE THREAD

**Issue by duttaditya18** [datboiee/flask-network#1]
@datboiee Assign me work in the issues section. I will work on it and make a PR. (Or just make me a contributor 😄 )

**Comment by datboiee** [comment]
Hangouts

**Comment by duttaditya18** [comment]
@datboiee Please use Github issues. It makes it a lot more convenient to refer back. Please.

**Comment by datboiee** [comment]
Okay

**Comment by datboiee** [comment]
@duttaditya18 no need to mention me every time

**Comment by datboiee** [comment]
So... 
I am not working on it right now coz ill have to learn a few libs

**Comment by duttaditya18** [comment]
Okay.

**Comment by datboiee** [comment]
I will start in abt 2 days

**Comment by duttaditya18** [comment]
Can you assign me work in any of the projects you've been working on?

**Comment by datboiee** [comment]
Or maybe even 1

**Comment by datboiee** [comment]
You can start working on the ui

**Comment by datboiee** [comment]
@duttaditya18 I added you as collaborator

**Comment by duttaditya18** [comment]
thx

**Comment by duttaditya18** [comment]
Make a new Issue saying what should be done.
